settings:
  base_save_dir: "./output/activations"
  base_classify_dir: "./output/classifications"
  batch_size: 10
  model_type: "llm"
  sae_location: "res"
  test_size: 0.4
  tree_depth: 5
  act_only: True
  cuda_visible_devices: "0,3,6,7"
  bow_baseline: "True"

models:
  - name: "google/gemma-2b"
    layers: [6, 12, 17]
    widths: ["16k"]

  - name: "google/gemma-2-2b"
    layers: [5, 12, 19]
    widths: ["16k", "65k"]


        # "AIM-Harvard/reject_prompts",
        # "jackhhao/jailbreak-classification",
        # "willcb/massive-intent",
        # "willcb/massive-scenario",
        # "legacy-datasets/banking77",
        # "SetFit/tweet_eval_stance_abortion",
datasets:
  - name: "Anthropic/election_questions"
    config_name: ""
    split: "test"
    text_field: "question"
    label_field: "label"
  - name: "AIM-Harvard/reject_prompts"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label"
  - name: "jackhhao/jailbreak-classification"
    config_name: ""
    split: "train"
    text_field: "prompt"
    label_field: "type"
  - name: "willcb/massive-intent"
    config_name: ""
    split: "train"
    text_field: "input"
    label_field: "label"
  - name: "willcb/massive-scenario"
    config_name: ""
    split: "train"
    text_field: "input"
    label_field: "label"
  - name: "legacy-datasets/banking77"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label"
  - name: "SetFit/tweet_eval_stance_abortion"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label_text"
# “LabHC/bias_in_bios_class_set1",
# “LabHC/bias_in_bios_class_set2",
# “LabHC/bias_in_bios_class_set3",
# “canrager/amazon_reviews_mcauley_1and5",
# “canrager/amazon_reviews_mcauley_1and5_sentiment",
# “codeparrot/github-code",
# “fancyzhx/ag_news",
# “Helsinki-NLP/europarl",
  - name: "LabHC/bias_in_bios"
    config_name: ""
    split: "train"
    text_field: "hard_text"
    label_field: "gender"
  - name: "canrager/amazon_reviews_mcauley_1and5"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "rating"
  - name: "codeparrot/github-code"
    config_name: ""
    split: "train"
    text_field: "code"
    label_field: "language"
  - name: "fancyzhx/ag_news"
    config_name: ""
    split: "train"
    text_field: "text"
    label_field: "label"

classification_params:
  top_n_values: [0, 20, 50]
  binarize_values: [null, 1.0]
  extra_top_n: -1
  extra_binarize_value: null

