#!/bin/bash
set -e
# CUDA_VISIBLE_DEVICES=4 uv run python -m attention_probe.train_mosaic --run_set h-attn --train_lbfgs=False &
# CUDA_VISIBLE_DEVICES=5 uv run python -m attention_probe.train_mosaic --run_set h-mean --take_mean=True &
# wait
# CUDA_VISIBLE_DEVICES=4 uv run python -m attention_probe.train_mosaic --run_set h-last --last_only=True
# CUDA_VISIBLE_DEVICES=0 uv run python -m attention_probe.train_mosaic --run_set h-attn-2 --train_lbfgs=False --n_heads=2 &
# CUDA_VISIBLE_DEVICES=1 uv run python -m attention_probe.train_mosaic --run_set h-attn-4 --train_lbfgs=False --n_heads=4 &
# wait
# CUDA_VISIBLE_DEVICES=0 uv run python -m attention_probe.train_mosaic --run_set h-attn-8 --train_lbfgs=False --n_heads=8 &
# CUDA_VISIBLE_DEVICES=1 uv run python -m attention_probe.train_mosaic --run_set h-attn-16 --train_lbfgs=False --n_heads=16 &

# CUDA_VISIBLE_DEVICES=2 uv run python -m attention_probe.train_mosaic --run_set hay-attn --train_lbfgs=False --cache_source output_haystack &
# CUDA_VISIBLE_DEVICES=3 uv run python -m attention_probe.train_mosaic --run_set hay-mean --take_mean=True --cache_source output_haystack &
# CUDA_VISIBLE_DEVICES=4 uv run python -m attention_probe.train_mosaic --run_set hay-last --last_only=True --cache_source output_haystack &
# CUDA_VISIBLE_DEVICES=5 uv run python -m attention_probe.train_mosaic --run_set hay-attn-2 --train_lbfgs=False --cache_source output_haystack --n_heads=2 &
# CUDA_VISIBLE_DEVICES=6 uv run python -m attention_probe.train_mosaic --run_set hay-attn-4 --train_lbfgs=False --cache_source output_haystack --n_heads=4 &
# CUDA_VISIBLE_DEVICES=7 uv run python -m attention_probe.train_mosaic --run_set hay-attn-8 --train_lbfgs=False --cache_source output_haystack --n_heads=8 &
# wait

# CUDA_VISIBLE_DEVICES=2 uv run python -m attention_probe.train_mosaic --run_set h-mean-adam --train_lbfgs=False --take_mean=True &
# CUDA_VISIBLE_DEVICES=3 uv run python -m attention_probe.train_mosaic --run_set h-mean-last --train_lbfgs=False --take_mean=True &

CUDA_VISIBLE_DEVICES=2 uv run python -m attention_probe.train_mosaic --run_set h-mean-cv --take_mean=True --use_linear_classifier=True &
CUDA_VISIBLE_DEVICES=2 uv run python -m attention_probe.train_mosaic --run_set h-last-cv --last_only=True --use_linear_classifier=True &

wait